module.exports.authValidation = require('./auth.validation')
module.exports.userValidation = require('./user.validation')
module.exports.businessValidation = require('./business.validation')
module.exports.customerValidation = require('./customer.validation')
module.exports.adminValidation = require('./admin.validation')